#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=20gb,walltime=0:30:00
#PBS -N app-mrtrix3-split-b0s
#PBS -V

time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./separate.sh

if [ ! -f ./dwi/dwi.nii.gz ]; then
	echo "failed"
	exit 1
else
	echo "complete"
	exit 0
fi
